version: 0.2

phases:
  build:
    commands:
      - echo "my build start .. for lambda zip .."
      - zip -r  mydeploy.zip  lambda_function.py 

  post_build:
    commands:
      - echo "deploy lambda zip function .."
      - aws  lambda  update-function-code  --function-name lwfunc1  --zip-file fileb://mydeploy.zip
